export const playerData = [
    {
        playerStats: [{
                playerLVL: 0,
                playerXP: 0,
                maxStorage: 5,
                playerMoney: 0,
                playerPearl: 0,
                playerOpenChest: 0,
                playerGotCommonChest: 0,
                playerGotRareChest: 0,
                playerGotEpicChest: 0,
                playerGotLegendaryChest: 0,
                playerGotMythicChest: 0,
                playerGotEtherealChest: 0,
                playerGotCelestialChest: 0,
                playerGotTranscendentChest: 0,
                playerCaughtCommonFish: 0,
                playerCaughtRareFish: 0,
                playerCaughtEpicFish: 0,
                playerCaughtLegendaryFish: 0,
                playerCaughtMythicFish: 0,
                playerCaughtEtherealFish: 0,
                playerCaughtCelestialFish: 0,
                playerCaughtTranscendentFish: 0,
                playerCaughtInfernoFish: 0,
                playerCaughtGlacierFish: 0,
                playerCaughtCycloneFish: 0,
                playerCaughtLightningFish: 0,
                playerCaughtNatureFish: 0,
                playerCaughtTreasure: 0,
                playerCaughtTrash: 0,
                playerTotalPlayerTime: 0,
            }],
        FishingRod: {
            lvl: 1,
            commonFish_chance: 100,
            rareFish_chance: 5,
            EpicFish_chance: 1,
            mythicFish_chance: 0,
            EtherealFish_chance: 0,
            celestiaFish_chance: 0,
            transcendentFish_chance: 0,
            infernoFish_chance: 0,
            glacierFish_chance: 0,
            cycloneFish_chance: 0,
            lightningFish_chance: 0,
            natureFish_chance: 0,
            commonChest_chance: 70,
            epicChest_chance: 10,
            rareChest_chance: 3,
            legendaryChest_chance: .000000009,
            mythicChest_chance: .0000000001,
            etherealChest_chance: 0,
            celestialChest_chance: 0,
            transcendentChest_chance: 0,
            Attachment: [{
                    rod_blank: 1,
                    rod_grip: 1,
                    rod_reel_seat: 1,
                    rod_reeling_speed: 1,
                    rod_guides: 1,
                    rod_tip: 1,
                    rod_butt: 1
                }],
            hookAttachment: [{
                    maxAttachment: 2
                }]
        },
        playerInventory: [{}]
    }
];
